from enum import Enum

class BayArea(Enum):
    EASTBAY = 'East Bay','EBY', 'https://sfbay.craigslist.org/search/eby/apa?',r'\b(?:alameda|albany / el cerrito|berkeley|berkeley north / hills|brentwood / oakley|concord / pleasant hill / martinez|danville / san ramon|dublin / pleasanton / livermore|emeryville|fairfield / vacaville|fremont / union city / newark|hayward / castro valley|hercules, pinole, san pablo, el sob|lafayette / orinda / moraga|oakland downtown|oakland east|oakland hills / mills|oakland lake merritt / grand|oakland north / temescal|oakland piedmont / montclair|oakland rockridge / claremont|oakland west|pittsburg / antioch|richmond / point / annex|san leandro|vallejo / benicia|walnut creek|east bay)\b'
    SANFRANCISCO = 'San Francisco','SFC','https://sfbay.craigslist.org/search/sfc/apa?',r'\b(?:alamo square / nopa|bayview|bernal heights|castro / upper market|cole valley / ashbury hts|downtown / civic / van ness|excelsior / outer mission|financial district|glen park|haight ashbury|hayes valley|ingleside / SFSU / CCSF|inner richmond|inner sunset / UCSF|laurel hts / presidio|lower haight|lower nob hill|lower pac hts|marina / cow hollow|mission district|nob hill|noe valley|north beach / telegraph hill|pacific heights|portola district|potrero hill|richmond / seacliff|russian hill|SOMA / south beach|sunset / parkside|tenderloin|treasure island|twin peaks / diamond hts|USF / panhandle|visitacion valley|west portal / forest hill|western addition|city of san francisco)\b'
    SOUTHBAY = 'South Bay', 'SBY','https://sfbay.craigslist.org/search/sby/apa?',r'\b(?:campbell|cupertino|gilroy|hollister|los gatos|milpitas|morgan hill|mountain view|san jose downtown|san jose east|san jose north|san jose south|san jose west|santa clara|saratoga|sunnyvale|willow glen / cambrian|south bay area)\b'
    NORTHBAY = 'North Bay', 'NBY','https://sfbay.craigslist.org/search/nby/apa?',r'\b(?:corte madera|fairfax|greenbrae|healdsburg / windsor|kentfield / ross|lake county|larkspur|mendocino county|mill valley|napa county|novato|petaluma|rohnert pk / cotati|russian river|san anselmo|san rafael|santa rosa|sausalito|sebastopol|sonoma|tiburon / belvedere|west marin|north bay / marin)\b'
    PENINSULA = 'Peninsula','PEN','https://sfbay.craigslist.org/search/pen/apa?',r'\b(?:atherton|belmont|brisbane|burlingame|coastside/pescadero|daly city|east palo alto|foster city|half moon bay|los altos|menlo park|millbrae|mountain view|pacifica|palo alto|portola valley|redwood city|redwood shores|san bruno|san carlos|san mateo|south san francisco|woodside|peninsula)\b'
    SANTACRUZ = 'Santa Cruz','SCZ','https://sfbay.craigslist.org/search/scz/apa?', r'\b(?:aptos|boulder creek|capitola|santa cruz|scotts valley|soquel|watsonville|santa cruz county)\b'
        
class Filters(Enum):
    HOUSING = r'\b(?:apartment|condo|cottage/cabin|duplex|flat|house|in-law|loft|townhouse|manufactured|assisted living|land)\b'
    LAUNDRY = r'\b(?:w/d in unit|w/d hookups|laundry in bldg|laundry on site|no laundry on site)\b'
    PETS = r'\b(?:"cats|dogs")\b'